# Generated by Django 5.2.3 on 2025-07-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('graduation_year', models.CharField(max_length=4)),
                ('diploma_number', models.CharField(max_length=20)),
                ('diploma_file', models.FileField(upload_to='diplomas/')),
                ('transcript_file', models.FileField(upload_to='transcripts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
