# Generated by Django 5.2.3 on 2025-07-03 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_diploma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_seriya', models.CharField(max_length=2)),
                ('passport_number', models.CharField(max_length=7)),
                ('passport_jshir', models.CharField(max_length=14)),
                ('cv_file', models.FileField(upload_to='cv_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
