# Generated by Django 5.2.3 on 2025-07-12 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_unique_number_requirement_userrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequirement',
            name='score',
        ),
        migrations.CreateModel(
            name='UserRequirementScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_scores', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.requirement')),
                ('user_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='users.userrequirement')),
            ],
        ),
    ]
