# Generated by Django 5.2.4 on 2025-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userrequirement_score_userrequirementscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequirement',
            name='score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
