# Generated by Django 5.2.4 on 2025-07-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userrequirement_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Xodim'), ('CONTROLLER', 'Baholovchi'), ('OBSERVER', 'Kuzatuvchi'), ('PARTICIPANT', 'Ishtirok etuvchi')], default='PARTICIPANT', max_length=20),
        ),
    ]
