version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vakansiyalar
      POSTGRES_USER: vakansiyalar
      POSTGRES_PASSWORD: vakansiyalar
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5440:5432"
  web:
    build: .
    command: gunicorn vakansiyalar.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=vakansiyalar
      - DJANGO_DB_USER=vakansiyalar
      - DJANGO_DB_PASSWORD=vakansiyalar
volumes:
  postgres_data:
